<?php
/**
 * Created by IntelliJ IDEA.
 * User: Sadako
 * Date: 2016/4/15
 * Time: 17:40
 */

/**
 * Implements hook_menu().
 */

$class="企业介绍";
function about_menu() {//全局变量无效、农业学校等只显示一所？
	$items ['about'] = array (
			'title' => '产业园基地',
			'page callback' => 'about_introduction_page_callback',
			'access callback' => TRUE,
			'type' => MENU_SUGGESTED_ITEM,
			'menu_name' => 'main-menu',
			'weight' => 50 
	);
	$items ['about/introduction'] = array (
			'title' => '企业介绍',
			'access callback' => TRUE,
			'type' => MENU_DEFAULT_LOCAL_TASK 
	);
	$items ['about/park'] = array (
			'title' => '园区风貌',
			'page callback' => 'about_park_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK 
	);
	;
	$items ['about/school'] = array (
			'title' => '农业学校',
			'page callback' => 'about_school_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK 
	);
	$items ['about/investors'] = array (
			'title' => '园区招商',
			'page callback' => 'about_investors_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK 
	);
	$items ['about/partners'] = array (
			'title' => '入驻企业',
			'page callback' => 'about_partners_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK 
	);
	return $items;
}
function about_introduction_page_callback() {
	global $user;
	global $class;
	$class="企业介绍";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid' 
	) )->condition ( 'type', "article" )->condition ( 'n.title', "企业介绍" )->condition ( 'status', '1' )->range ( 0, 1 )->orderBy ( 'created', 'ASC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$html = '';
	foreach ( $nodes as $node ) {
		$html .= $node->body ['und'] [0] ['value'];
	}
	$pagehtml = <<<EOS
<section class="w80">
        <div class="bar">
            <h1>企业介绍</h1>
        </div>
        <div style="text-align:center">
            <video controls preload>
                <source src="$module_path/videos/video0.webm" />
                <source src="$module_path/videos/video0.mov" />
            </video>
        </div>
        </br>
        $html
</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $pagehtml 
	) );
}
function about_park_page_callback() {
	global $user;
	global $class;
	$class="园区风貌";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid'
	) )->condition ( 'type', "article" )->condition ( 'n.title', "园区风貌" )->condition ( 'status', '1' )->range ( 0, 5 )->orderBy ( 'created', 'DEC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$bodyhtml = '';
	foreach ( $nodes as $node ) {
		if(isset($node->field_image)){
			foreach ($node->field_image['und'] as $img){
				$bodyhtml.='<img class="showcaseImg" src="'.file_create_url($img['uri']).'"/>';
			}
		}
		if(isset($node->body)){
			$bodyhtml .= $node->body ['und'] [0] ['value'];
		}
	}
	$parkhtml =<<<EOS
	<section class="w80">
			<div class="bar">
				<h1>园区风貌</h1>
			</div>
			$bodyhtml
		</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $parkhtml 
	) );
}
function about_school_page_callback() {
	global $user;
	global $class;
	$class="农业学校";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid'
	) )->condition ( 'type', "article" )->condition ( 'n.title', "农业学校" )->condition ( 'status', '1' )->range ( 0, 1 )->orderBy ( 'created', 'DEC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$bodyhtml = '';
	foreach ( $nodes as $node ) {
		if(isset($node->field_image)){
			$bodyhtml.='<img class="w40 floatRight marginLeft marginBottom" src="'.file_create_url($node->field_image ['und'] [0] ['uri']).'"/>';
		}
		if(isset($node->body)){
			$bodyhtml .= $node->body ['und'] [0] ['value'];
		}
	}
	$schoolhtml = <<<EOS
 <section class="w80">
    <div class="bar">
        <h1>农业学校</h1>
    </div>
    <div>
	    $bodyhtml
    </div>
</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $schoolhtml 
	) );
}
function about_investors_page_callback() {
	global $user;
	global $class;
	$class="园区招商";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid'
	) )->condition ( 'type', "article" )->condition ( 'n.title', "园区招商" )->condition ( 'status', '1' )->range ( 0, 1 )->orderBy ( 'created', 'DEC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$bodyhtml = '';
	foreach ( $nodes as $node ) {
		if(isset($node->field_image)){
			$bodyhtml.='<img class="w100" src="'.file_create_url($node->field_image ['und'] [0] ['uri']).'"/>';
		}
		if(isset($node->body)){
			$bodyhtml .= $node->body ['und'] [0] ['value'];
		}
	}
	$investorshtml =<<<EOS
	<section class="w80">
			<div class="bar">
				<h1>园区招商</h1>
			</div>
			$bodyhtml
		</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $investorshtml 
	) );
}
function about_partners_page_callback() {
	global $user;
	global $class;
	$class="入驻企业";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid'
	) )->condition ( 'type', "article" )->condition ( 'n.title', "入驻企业" )->condition ( 'status', '1' )->range ( 0, 1 )->orderBy ( 'created', 'DEC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$bodyhtml = '';
	foreach ( $nodes as $node ) {
		if(isset($node->field_image)){
			$bodyhtml.='<img class="w100" src="'.file_create_url($node->field_image ['und'] [0] ['uri']).'"/>';
		}
		if(isset($node->body)){
			$bodyhtml .= $node->body ['und'] [0] ['value'];
		}
	}
	$partners =<<<EOS
	<section class="w80">
			<div class="bar">
				<h1>入驻企业</h1>
			</div>
			$bodyhtml		
	</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $partners 
	) );
}

/**
 * Implements hook_theme()
 */
function about_theme() {
	global $class;
	$sql = "SELECT m.load_functions, m.to_arg_functions, m.access_callback, m.access_arguments, m.page_callback, m.page_arguments, m.delivery_callback, m.title, m.title_callback, m.title_arguments, m.type, m.description, ml.*
    				FROM {menu_links} ml LEFT JOIN {menu_router} m ON m.path = ml.router_path
    				WHERE ml.menu_name = :menu
    				ORDER BY p1 ASC, p2 ASC, p3 ASC, p4 ASC, p5 ASC, p6 ASC, p7 ASC, p8 ASC, p9 ASC";
	$result = db_query ( $sql, array (
			':menu' => 'main-menu' 
	), array (
			'fetch' => PDO::FETCH_ASSOC 
	) );
	$links = array ();
	foreach ( $result as $item ) {
		$links [] = $item;
	}
	$tree = menu_tree_data ( $links );
	$menu_links = '<nav id="sideNav" class="w20"><ul>';
	foreach ( $tree as $menu_item ) {
		if (! empty ( $menu_item ['link'] ['title'] ) && $menu_item ['link'] ['title'] == '产业园基地') {
			$sublink = $menu_item ['below'];
			foreach ( $sublink as $sublinkitem ) {
				if($sublinkitem ['link'] ['title']==$class){
					$menu_links .='<li class="activeNavItem">';
				}
				else {
					$menu_links .='<li>';
				}
				$menu_links .= '<a href="?q=' . $sublinkitem ['link'] ['link_path'] . '">' . $sublinkitem ['link'] ['title'] . '</a></li>';
			}
		}
	}
	$menu_links .= '</ul></nav>';
	return array (
			'aboutpage_page' => array (
					'template' => 'aboutpage',
					'variables' => array (
							'sidebarleft' => $menu_links 
					) 
			) 
	);
}
