<?php
/**
 * Created by IntelliJ IDEA.
 * User: Sadako
 * Date: 2016/4/15
 * Time: 17:40
 */

/**
 * Implements hook_menu().
 */

function about_menu() {
	$items ['about'] = array (
			'title' => '产业园基地',
			'page callback' => 'about_introduction_page_callback',
			'access callback' => TRUE,
			'type' => MENU_SUGGESTED_ITEM,
			'menu_name' => 'main-menu',
			'weight' => 45 
	);
	$items ['about/introduction'] = array (
			'title' => '企业介绍',
			'access callback' => TRUE,
			'type' => MENU_DEFAULT_LOCAL_TASK, 
			'weight' => 45 
	);
	$items ['about/park'] = array (
			'title' => '园区风貌',
			'page callback' => 'about_park_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK ,
			'weight' => 35 
	);
	;
	$items ['about/school'] = array (
			'title' => '农业学校',
			'page callback' => 'about_school_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK, 
			'weight' => 25 
	);
	$items ['about/investors'] = array (
			'title' => '园区招商',
			'page callback' => 'about_investors_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK, 
			'weight' => 15 
	);
	$items ['about/partners'] = array (
			'title' => '入驻企业',
			'page callback' => 'about_partners_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK, 
			'weight' => 5 
	);
	$items ['about/recruitment'] = array (
			'title' => '人才招聘',
			'page callback' => 'about_recruitment_page_callback',
			'access callback' => TRUE,
			'type' => MENU_LOCAL_TASK, 
			'weight' => 0 
	);
	return $items;
}
function about_introduction_page_callback() {
	global $user;
	$class="企业介绍";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid' 
	) )->condition ( 'type', "article" )->condition ( 'n.title', "企业介绍" )->condition ( 'status', '1' )->range ( 0, 1 )->orderBy ( 'created', 'ASC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$html = '';
	foreach ( $nodes as $node ) {
		$html .= (isset($node->body[LANGUAGE_NONE]) && isset($node->body[LANGUAGE_NONE][0])) ? $node->body[LANGUAGE_NONE][0]['value'] : '';
	}
	$pagehtml = <<<EOS
<section class="w80">
        <div class="bar w80">		
			<img class="icon" src="$module_path/images/icons/about.png">
			<h1>企业介绍</h1>
		</div>
        <div style="text-align:center">
            <video controls preload>
                <source src="$module_path/videos/video0.webm" />
                <source src="$module_path/videos/video0.mov" />
            </video>
        </div>
        </br>
        $html
</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $pagehtml,
			"sidebarleft"=>get_sidebar_menu_list($class), 
	) );
}
function about_park_page_callback() {
	global $user;
	$class="园区风貌";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid'
	) )->condition ( 'type', "article" )->condition ( 'n.title', "园区风貌" )->condition ( 'status', '1' )->range ( 0, 5 )->orderBy ( 'created', 'DEC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$bodyhtml = '';
	foreach ( $nodes as $node ) {
		if(isset($node->field_image) && isset($node->field_image[LANGUAGE_NONE]) ){
			foreach ($node->field_image[LANGUAGE_NONE] as $img){
				$bodyhtml.='<img class="showcaseImg" src="'.file_create_url($img['uri']).'"/>';
			}
		}
		if(isset($node->body) && isset($node->body [LANGUAGE_NONE]) && isset($node->body [LANGUAGE_NONE][0])){
			$bodyhtml .= $node->body [LANGUAGE_NONE][0]['value'];
		}
	}
	$parkhtml =<<<EOS
	<section class="w80">
			<div class="bar w80">		
				<img class="icon" src="$module_path/images/icons/about_park.png">
				<h1>园区风貌</h1>
			</div>
			$bodyhtml
		</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $parkhtml ,
			"sidebarleft"=>get_sidebar_menu_list($class),
	) );
}
function about_school_page_callback() {
	global $user;
	$class="农业学校";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid'
	) )->condition ( 'type', "article" )->condition ( 'n.title', "农业学校" )->condition ( 'status', '1' )->range ( 0, 1 )->orderBy ( 'created', 'DEC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$bodyhtml = '';
	foreach ( $nodes as $node ) {
		if(isset($node->field_image)&&isset($node->field_image[LANGUAGE_NONE])&&isset($node->field_image[LANGUAGE_NONE][0])){
			$bodyhtml.='<img class="w40 floatRight marginLeft marginBottom" src="'.file_create_url($node->field_image[LANGUAGE_NONE][0]['uri']).'"/>';
		}
		if(isset($node->body)){
			$bodyhtml .= (isset($node->body[LANGUAGE_NONE]) && isset($node->body[LANGUAGE_NONE][0])) ? $node->body[LANGUAGE_NONE][0]['value'] : '';
		}
	}
	$schoolhtml = <<<EOS
 <section class="w80">
    <div class="bar w80">		
		<img class="icon" src="$module_path/images/icons/about_school.png">
		<h1>农业学校</h1>
	</div>
    <div>
	    $bodyhtml
    </div>
</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $schoolhtml ,
			"sidebarleft"=>get_sidebar_menu_list($class),
	) );
}
function about_investors_page_callback() {
	global $user;
	$class="园区招商";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid'
	) )->condition ( 'type', "article" )->condition ( 'n.title', "园区招商" )->condition ( 'status', '1' )->range ( 0, 1 )->orderBy ( 'created', 'DEC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$bodyhtml = '';
	foreach ( $nodes as $node ) {
		if(isset($node->field_image)&&isset($node->field_image[LANGUAGE_NONE])&&isset($node->field_image[LANGUAGE_NONE][0])){
			$bodyhtml.='<img class="w100" src="'.file_create_url($node->field_image[LANGUAGE_NONE][0]['uri']).'"/>';
		}
		if(isset($node->body)){
			$bodyhtml .= (isset($node->body[LANGUAGE_NONE]) && isset($node->body[LANGUAGE_NONE][0])) ? $node->body[LANGUAGE_NONE][0]['value'] : '';
		}
	}
	$investorshtml =<<<EOS
	<section class="w80">
			<div class="bar w80">		
				<img class="icon" src="$module_path/images/icons/about_investors.png">
				<h1>园区招商</h1>
			</div>
			$bodyhtml
		</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $investorshtml ,
			"sidebarleft"=>get_sidebar_menu_list($class),
	) );
}
function about_partners_page_callback() {
	global $user;
	$class="入驻企业";
	$module_path = drupal_get_path ( 'module', 'about' );
	$query = db_select ( 'node', 'n' );
	$nids = $query->fields ( 'n', array (
			'nid'
	) )->condition ( 'type', "article" )->condition ( 'n.title', "入驻企业" )->condition ( 'status', '1' )->range ( 0, 1 )->orderBy ( 'created', 'DEC' )->addTag ( 'node_access' )->execute ()->fetchCol ();
	$nodes = node_load_multiple ( $nids );
	$bodyhtml = '';
	foreach ( $nodes as $node ) {
		if(isset($node->field_image)&&isset($node->field_image[LANGUAGE_NONE])&&isset($node->field_image[LANGUAGE_NONE][0])){
			$bodyhtml.='<img class="w100" src="'.file_create_url($node->field_image[LANGUAGE_NONE][0]['uri']).'"/>';
		}
		if(isset($node->body)){
			$bodyhtml .= (isset($node->body[LANGUAGE_NONE]) && isset($node->body[LANGUAGE_NONE][0])) ? $node->body[LANGUAGE_NONE][0]['value'] : '';
		}
	}
	$partners =<<<EOS
	<section class="w80">
			<div class="bar w80">			
				<img class="icon" src="$module_path/images/icons/about_partners.png">
				<h1>入驻企业</h1>
			</div>
			$bodyhtml		
	</section>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $partners ,
			"sidebarleft"=>get_sidebar_menu_list($class),
	) );
}
function about_recruitment_page_callback(){
	global $user;
	$class="人才招聘";
	
	$module_path = drupal_get_path ( 'module', 'about' );
	//dany add at 2016-05-14
	$recruitList=array();
    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query
    ->fields('n', array('nid', 'created'))
    ->condition('type', 'recruitment')
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->addTag('node_access')
    ->execute()
    ->fetchCol();

    if (!empty($nids)) {
        $nodes = node_load_multiple($nids);
        foreach ($nodes as $key => $node) 
		{
            $recruitList[]=array(
				'request_num'	=> $node->field_recruit_num[LANGUAGE_NONE][0]['value'],
        		'title'			=> $node->title,
				'createDate'	=> date('y-m-d',$node->created),
				'content'		=> (isset($node->body[LANGUAGE_NONE]) && isset($node->body[LANGUAGE_NONE][0])) ? $node->body[LANGUAGE_NONE][0]['value'] : '',
			);
		}
    }
	$recruitmenttml=<<<EOS
	<div class="bar w80">
		<img class="icon" src="$module_path/images/icons/hiring_icon.png">
		<h1>人才招聘</h1>
	</div>
	<section class="w80">
EOS;
	foreach ($recruitList as $key => $recruitment) {
		$recruitmenttml.='<div class="jobItem" id="jobItem"'.$key.'>'.
				'<h3>'.
				$recruitment['title'].
				'（'.$recruitment['request_num'].'名）</h3><img class="floatRight" src="'.$module_path.'/images/icons/arrow_down.png">
				<p class="floatRight marginRight">发布于 '.$recruitment['createDate'].'</p>
				<div class="hideModal" id="describe0">'.
					$recruitment['content'].
				'</div>
			</div>';
	}
	$recruitmenttml.=<<<EOS
	</section>
		<script type="text/javascript">
		      $('.jobItem').click(function(){
		        var index = $('.jobItem').index($(this));
		        $('.hideModal:eq('+index+')').slideToggle('slow',function(){
		            var rotateValue = 180;
		            if ($(this).is(':hidden')) {
		                rotateValue = 0;
		            }
		            $('.jobItem:eq('+index+')').find('img').css('transition','transform .5s');
		            $('.jobItem:eq('+index+')').find('img').css('transform','rotate('+rotateValue+'deg)');  
		        });
		      });
		</script>
EOS;
	return theme ( "aboutpage_page", array (
			"pagemain" => $recruitmenttml ,
			"sidebarleft"=>get_sidebar_menu_list($class),
	) );
}
/**
 * Implements hook_theme()
 */
function about_theme() {
	return array (
			'aboutpage_page' => array (
					'template' => 'aboutpage',
					'variables' => array (
					) 
			) 
	);
}

function second_menu_sort_weights($link1, $link2) {
	return $link1['link']['weight'] < $link2['link']['weight'] ? 1 : 0;
}

function get_sidebar_menu_list($class){
	$sql = "SELECT m.load_functions, m.to_arg_functions, m.access_callback, m.access_arguments, m.page_callback, m.page_arguments, m.delivery_callback, m.title, m.title_callback, m.title_arguments, m.type, m.description, ml.*
    				FROM {menu_links} ml LEFT JOIN {menu_router} m ON m.path = ml.router_path
    				WHERE ml.menu_name = :menu
    				ORDER BY p1 ASC, p2 ASC, p3 ASC, p4 ASC, p5 ASC, p6 ASC, p7 ASC, p8 ASC, p9 ASC";
	$result = db_query ( $sql, array (
			':menu' => 'main-menu'
	), array (
			'fetch' => PDO::FETCH_ASSOC
	) );
	$links = array ();
	foreach ( $result as $item ) {
		$links [] = $item;
	}
	$tree = menu_tree_data ( $links );
	$menu_links = '<nav id="sideNav" class="w20"><ul>';
	foreach ( $tree as $menu_item ) {
		if (! empty ( $menu_item ['link'] ['title'] ) && $menu_item ['link'] ['title'] == '产业园基地') {
			$sublink = $menu_item ['below'];
			uasort($sublink, "second_menu_sort_weights");
			foreach ( $sublink as $sublinkitem ) {
				if($sublinkitem ['link'] ['title']==$class){
					$menu_links .='<li class="activeNavItem">';
				}
				else {
					$menu_links .='<li>';
				}
				$menu_links .= '<a href="' . url($sublinkitem ['link'] ['link_path']) . '">' . $sublinkitem ['link'] ['title'] . '</a></li>';
			}
		}
	}
	$menu_links .= '</ul></nav>';
	return $menu_links;
}
