<?php
/**
 * Created by IntelliJ IDEA.
 * User: Sadako
 * Date: 2016/4/15
 * Time: 17:40
 */

/**
 * Implements hook_menu().
 */
function farmshow_menu() {
    $items['farmshow'] = array(
        'title' =>'农业展馆',
        'page pagecallback' => 'farmshow_leisurefarm_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'menu_name' => 'main-menu',
        'weight'=>2,
    );
    $items['farmshow/leisurefarm'] = array(//创建子菜单
        'title' =>'休闲农庄',
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['farmshow/product'] = array(
        'title' =>'农业展品',
        'page callback' => 'farmshow_product_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
    $items['farmshow/forum'] = array(
        'title' =>'农业展馆论坛',
        'page callback' => 'farmshow_forum_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
    return $items;
}

function farmshow_leisurefarm_page_callback() {
    $module_path = drupal_get_path('module', 'farmshow');
    drupal_add_css($module_path . '/css/farmshow.css');
    // drupal_add_js();
    return theme("farmproduct_page", array('imglink' => 'http://img.png'));
}

function farmshow_product_page_callback() {
    return "Hello world1";
}

function farmshow_forum_page_callback() {
    $product=array();
    $recommend=array();
    $favorites=array();
    $recently_visited=array();
    return theme('farmproduct_page',array());
}

/**
 * Implements hook_theme()
 */
function farmshow_theme() {
    return array(
        'farmproduct_page' => array(
//            'variables' => array('content'=>null,'sidebarleft'=>NULL),
            'template' => 'farmproduct',//返回这个模板
        ),
    );
}

/**
 * Processes variables for member-page.tpl.php.
 *
 * @param $variables
 *   An associative array containing the following key:
 *   - sidebarleft
 *   - content
 *
 * @see farmproduct.tpl.php
 */
function template_preprocess_farmproduct_page(&$variables) {
    $variables['product']=null;
    $variables['recommend']=null;
    $variables['favorites']=null;
    $variables['recently_visited']=null;
}