<?php
/**
 * Create by Visual Studio Code
 * Author : Dany
 * E-mail : ifeifei@stu.xmu.edu.cn
 * Data = 2016-04-15 18:26
 */
 
/**
 * Implements hook_menu()
 */
function news_menu(){
    $items['news'] = array(
        'title' => t('品牌论坛'),
        'page callback' => 'news_allnews_page_callback',
        'access callback' => TRUE,
        'weight'=>20,
        'type' => MENU_SUGGESTED_ITEM,
        'menu_name' => 'main-menu',
    );
    $items['news/allnews']=array(
        'title' => t('品牌论坛'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['news/news66']=array(
        'title' => t('6.6涂岭论坛'),
        'page callback' => 'news_news66_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
    $items['news/news1212']=array(
        'title' => t('12.12电商论坛'),
        'page callback' => 'news_news1212_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
    $items['news/newsxinhui']=array(
        'title' => t('海促会咨询'),
        'page callback' => 'news_newsxinhui_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
    return $items;
}

function news_allnews_page_callback()
{
    drupal_add_js(drupal_get_path('module','news').'/js/newsaction.js');
    return theme("allNews_page", array());
}

function news_news66_page_callback()
{
    return theme("allNews_page", array());
}

function news_news1212_page_callback()
{
    return theme("allNews_page", array());
}

function news_newsxinhui_page_callback()
{
    return theme("allNews_page", array());
}

/**
 * Implements hook_theme()
 */
function news_theme() {
    return array(
        'allNews_page'  => array(
            'variables'=> array('newsTitle'=>'品牌论坛'),
            'template' => 'allNews',
        ),
        'new66_page' => array(
            'variables'=> array('newsTitle'=>'6.6涂岭论坛'),
            'template' => 'allNews',
        ),
        'news1212_page' => array(
            'variables'=> array('newsTitle'=>'12.12电商论坛'),
            'template' => 'allNews',
        ),
        'newsXinhui_page' => array(
            'variables'=> array('newsTitle'=>'海促会资讯'),
            'template' => 'allNews',
        ),
    );
}

function template_preprocess_allNews_page(&$variables) {
    $module_path = drupal_get_path('module','news');
    $variables['imageLinkPathHead']=$module_path;
    
    //测试使用数据
    $build = array();
    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query
    ->fields('n', array('nid', 'created'))
    ->condition('type', 'zi_xun')
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->limit(variable_get('default_nodes_main', 10))
    ->addTag('node_access')
    ->execute()
    ->fetchCol();

    if (!empty($nids)) {
        $nodes = node_load_multiple($nids);
        $build += node_view_multiple($nodes);
        $build['pager'] = array(
        '#theme' => 'pager',
        '#weight' => 5,
        );
    }
    foreach(range(0,4) as $value)
    {
        $magzineList[$value]=array(
        'imgurl'      => 'images/magazine/magazine.jpg',
        'date' => 'Jackie Chan'.$value,
        'title'    => 'farmName1'.$value,
        'content'   => $value,
        );
    }
    foreach(range(0,4) as $value)
    {
        $noteList[$value]=array(
        'imgurl'      => 'images/news/6.6/6.6_1.jpg',
        'date' => '22 MAR',
        'title'    => '台湾',
        'content'   => '<p>
				海促会主席吕双辉介绍说，今年将以交流活动为主，以展会为辅。今年涂岭交流活动的主题确定为“台湾休闲农业的创新与创业”，邀请两岸休闲农业规划设计专家、专业技术员、休闲农业的成功经营者，从规划设计、创意、发展趋势等角度，现场解读休闲农业的“创新经营之道”。
			</p>
			<p>
				“今年涂岭交流活动主推休闲农业，将起到抛砖引玉的作用。”海促会副秘书长叶华镛说，以此次交流活动为契机，新辉大电子商务产业园将引进台湾生态农业，率先在泉港区打造休闲农业示范园。
			</p>
			<p>
				当天，新辉大电子商务产业园区将与台湾台中市和平区农会产销联盟签订水果嫁接技术合作协议；与台湾新世膜科技股份有限公司签订有机水产养殖协议；与台湾中州科技大学签订农产品深加工及学术研究协议；与台湾讯玛国际股份有限公司签订植物工厂合作协议；与台湾高雄市燕巢合作农场签订休闲农场合作开发协议等，为休闲农业示范园奠定扎实的技术基础，将来实现整场技术输出，在全国各地复制式地推广。
			</p>
			<p>
				目前，休闲农业示范园的相关工作正在筹备中。主席吕双辉说，休闲农业示范园将结合人文、生态、教育、医保、环保、文创等多元化经营模式，打造多功能的休闲观光园区，未来将在国内起到辐射和示范效应。
			</p>
            <p>
				海促会主席吕双辉介绍说，今年将以交流活动为主，以展会为辅。今年涂岭交流活动的主题确定为“台湾休闲农业的创新与创业”，邀请两岸休闲农业规划设计专家、专业技术员、休闲农业的成功经营者，从规划设计、创意、发展趋势等角度，现场解读休闲农业的“创新经营之道”。
			</p>
			<p>
				“今年涂岭交流活动主推休闲农业，将起到抛砖引玉的作用。”海促会副秘书长叶华镛说，以此次交流活动为契机，新辉大电子商务产业园将引进台湾生态农业，率先在泉港区打造休闲农业示范园。
			</p>
			<p>
				当天，新辉大电子商务产业园区将与台湾台中市和平区农会产销联盟签订水果嫁接技术合作协议；与台湾新世膜科技股份有限公司签订有机水产养殖协议；与台湾中州科技大学签订农产品深加工及学术研究协议；与台湾讯玛国际股份有限公司签订植物工厂合作协议；与台湾高雄市燕巢合作农场签订休闲农场合作开发协议等，为休闲农业示范园奠定扎实的技术基础，将来实现整场技术输出，在全国各地复制式地推广。
			</p>
			<p>
				目前，休闲农业示范园的相关工作正在筹备中。主席吕双辉说，休闲农业示范园将结合人文、生态、教育、医保、环保、文创等多元化经营模式，打造多功能的休闲观光园区，未来将在国内起到辐射和示范效应。
			</p>',
        );
    }
    
    $variables['noteList']=$noteList;
    $variables['magzineList']=$magzineList;
}
