<?php
/**
 * Create by Visual Studio Code
 * Author : Dany
 * E-mail : ifeifei@stu.xmu.edu.cn
 * Data = 2016-04-15 18:26
 */
 
/**
 * Implements hook_menu()
 */
function news_menu(){
    $items['news'] = array(
        'title' => t('品牌论坛'),
        'page callback' => 'news_allnews_page_callback',
        'access callback' => TRUE,
        'weight'=>20,
        'type' => MENU_SUGGESTED_ITEM,
        'menu_name' => 'main-menu',
    );
    $items['news/allnews']=array(
        'title' => t('品牌论坛'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['news/news66']=array(
        'title' => t('6.6涂岭论坛'),
        'page callback' => 'news_news66_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
    $items['news/news1212']=array(
        'title' => t('12.12电商论坛'),
        'page callback' => 'news_news1212_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
    $items['news/newsxinhui']=array(
        'title' => t('海促会咨询'),
        'page callback' => 'news_newsxinhui_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5,
    );
    return $items;
}

function news_allnews_page_callback()
{
    $noteList=getNoteList('品牌论坛');
    return theme("allNews_page", array(
        'noteList'  => $noteList,
    ));
}

function news_news66_page_callback()
{
    $noteList=getNoteList('66涂岭论坛');
    return theme("allNews_page", array(
        'noteList'  => $noteList,
    ));
}

function news_news1212_page_callback()
{
    $noteList=getNoteList('1212电商论坛');
    return theme("allNews_page", array(
        'noteList'  => $noteList,
    ));
}

function news_newsxinhui_page_callback()
{
    $noteList=getNoteList('海促会资讯');
    return theme("allNews_page", array(
        'noteList'  => $noteList,
    ));
}

/**
 * Implements hook_theme()
 */
function news_theme() {
    return array(
        'allNews_page'  => array(
            'variables'=> array('newsTitle'=>'品牌论坛'),
            'template' => 'allNews',
        ),
        'new66_page' => array(
            'variables'=> array('newsTitle'=>'6.6涂岭论坛'),
            'template' => 'allNews',
        ),
        'news1212_page' => array(
            'variables'=> array('newsTitle'=>'12.12电商论坛'),
            'template' => 'allNews',
        ),
        'newsXinhui_page' => array(
            'variables'=> array('newsTitle'=>'海促会资讯'),
            'template' => 'allNews',
        ),
    );
}

function template_preprocess_allNews_page(&$variables) {
    $module_path = drupal_get_path('module','news');
    $variables['imageLinkPathHead']=$module_path;
    
    foreach(range(0,4) as $value)
    {
        $magzineList[$value]=array(
        'imgurl'      => 'images/magazine/magazine.jpg',
        'date' => 'Jackie Chan'.$value,
        'title'    => 'farmName1'.$value,
        'content'   => $value,
        );
    }
    $variables['magzineList']=$magzineList;
}


//util function
function getNoteList($type)
{
    $noteList=array();
    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query
    ->fields('n', array('nid', 'created'))
    ->condition('type', 'front_news')
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->addTag('node_access')
    ->execute()
    ->fetchCol();

    if (!empty($nids)) {
        $nodes = node_load_multiple($nids);
        foreach ($nodes as $key => $node) {
            if($node->field_news_type[LANGUAGE_NONE][0]['value']==$type)
            {
                $imgid = $node->field_image[LANGUAGE_NONE][0]['fid'];
                $imgfile = file_load($imgid);
                $imageurl = file_create_url($imgfile->uri);
                $noteList[$key]=array(
                    'imgurl'      => $imageurl,
                    'date'        => changeDateform(date('m-d',$node->created)),
                    'title'       => $node->title,
                    'content'     => $node->body[LANGUAGE_NONE][0]['value'],
                );
            }
        }
    }
    return $noteList;
}

function changeDateform($date)
{
    $m_d=explode("-",$date);
    switch($m_d[0])
    {
        case "01" :
        $month="Jan";
        break;   
        case "02" :
        $month="Feb";
        break;
        case "03" :
        $month="Mar";
        break;  
        case "04" :
        $month="Apr";
        break;
        case "05" :
        $month="May";
        break;  
        case "06" :
        $month="Jun";
        break;
        case "07" :
        $month="Jul";
        break;  
        case "08" :
        $month="Aug";
        break;
        case "09" :
        $month="Sep";
        break;  
        case "10" :
        $month="Oct";
        break;
        case "11" :
        $month="Nov";
        break;  
        case "12" :
        $month="Dec";
        break;
    }
    $day=$m_d[1];
    return $date.$month;
}
