<?php
/**
 * @file
 * Create a member page
 * @author Wang Xiaoli (creator)
 */

/**
 * Implements hook_menu().
 */
function member_menu() {
  $items['member'] = array(
    'title' => t('Members'),
    'page callback' => 'member_page_callback',
    'access callback' => TRUE,
	'type' 			  => MENU_NORMAL_ITEM,
   	'menu_name' 	  => 'main-menu',
	'weight' 		  => 3,
  );
  
  return $items;
}

function member_page_callback() {
  $build['content']['member_page'] = array(
	'#markup' => theme('member_page'),
  );
  return $build;
}

/**
 * Implements hook_theme()
 */
function member_theme() {
	return array(
		'member_page' => array(
	    	'variables' => array(),
	    	'template' => 'member-page',
	    ),
	);
}

/**
 * Processes variables for member-page.tpl.php.
 *
 * @param $variables
 *   An associative array containing the following key:
 *   - link
 *   - content
 *
 * @see member-page.tpl.php
 */
//function template_preprocess_member_page(&$variables) {
//  $variables['link'] = url("member");
 // $variables['content'] = 'Member page';
 //}

