<?php
/**
 * Create by Visual Studio Code
 * Author : Dany
 * E-mail : ifeifei@stu.xmu.edu.cn
 * Data = 2016-04-16 16:16
 */
 
 /**
  * Implements hook_menu()
  */
function classes_menu(){
    $items['classes'] = array(
        'title' => t('Classes'),
        'page callback' => 'classes_class_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    $items['classes/class'] = array(
        'title' => t('Recomanded Class'),
        'type' => MENU_LOCAL_TASK,
    );
    $items['classes/teachers'] = array(
        'title' => t('Famous Teachers'),
        'page callback' => 'classes_teacher_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    return $items;
}

function classes_class_page_callback() {
    $module_path = drupal_get_path('module', 'classes');
    return theme("classes_page", array());
}

function classes_teacher_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("teachers_page", array());
}

/**
 * Implements hook_theme()
 */
function classes_theme() {
    return array(
        'classes_page'  => array(
            'variables'=> array(),
            'template' => 'classes',
        ),
        'teachers_page' => array(
            'variables'=> array(),
            'template' => 'teachers',
        ),
    );
}

function template_preprocess_classes_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    $variables['imageLinkPathHead']=$module_path;
    //测试使用的数据，应该从数据库获取
    foreach(range(0,4) as $value)
    {
        $productList[$value]=array(
        'imgurl'      => 'images/farms/product-list.jpg',
        'productName' => 'productName1'.$value,
        'farmName'    => 'farmName1'.$value,
        'customers'   => $value,
        'comments'    => 'comments1.$value'
        );
    }
    drupal_add_css($module_path.'/css/class_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    drupal_add_js($module_path.'/js/scripts.js');
    $variables['classList']=$productList;
}

function template_preprocess_teachers_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    $variables['imageLinkPathHead']=$module_path;
    //测试使用的数据，应该从数据库获取
    foreach(range(0,4) as $value)
    {
        $productList[$value]=array(
        'imgurl'      => 'images/teachers/teacher0_thumb.jpg',
        'teacherName' => 'Jackie Chan'.$value,
        'farmName'    => 'farmName1'.$value,
        'customers'   => $value,
        'comments'    => 'comments1.$value'
        );
    }
    drupal_add_css($module_path.'/css/class_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    drupal_add_js($module_path.'/js/scripts.js');
    $variables['teacherList']=$productList;
}