<?php
/**
 * Create by Visual Studio Code
 * Author : Dany
 * E-mail : ifeifei@stu.xmu.edu.cn
 * Data = 2016-04-16 16:16
 */
 
 /**
  * Implements hook_menu()
  */
function classes_menu(){
    $items['classes'] = array(
        'title' => '新农人培训',
        'page callback' => 'classes_class_page_callback',
        'access callback' => TRUE,
        'weight'=>30,
        'type' => MENU_SUGGESTED_ITEM,
        'menu_name' => 'main-menu',
    );
    $items['classes/class'] = array(
        'title' => t('农业课堂'),
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
    );
    $items['classes/teachers'] = array(
        'title' => t('农业名师'),
        'page callback' => 'classes_teacher_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    $items['classes/campus'] = array(
        'title' => t('创业园地'),
        'page callback' => 'classes_campus_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    $items['classes/admission'] = array(
        'title' => t('招生信息'),
        'page callback' => 'classes_admission_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    $items['classes/files'] = array(
        'title' => t('资料下载'),
        'page callback' => 'classes_files_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    $items['classes/detailclass/%'] = array(
        'title' => t('详细内容'),
        'page callback' => 'classes_detailclass_page_callback',
        'page arguments'=> array(2),
        'access callback' => TRUE,
        'menu_name' => 'user-menu',
    );
    $items['classes/detailteacher/%'] = array(
        'title' => t('详细内容'),
        'page callback' => 'classes_detailteacher_page_callback',
        'page arguments'=> array(2),
        'access callback' => TRUE,
        'menu_name' => 'user-menu',
    );    
    return $items;
}

/*
 * functions of page callback
 */
function classes_class_page_callback() {
    $module_path = drupal_get_path('module', 'classes');
    return theme("classes_page", array());
}

function classes_teacher_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("teachers_page", array());
}

function classes_campus_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("campus_page", array());
}

function classes_admission_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("admission_page", array());
}

function classes_files_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("files_page", array());
}

function classes_detailclass_page_callback($nid){
    $node=node_load($nid);
    $class=array();
    $vedioid = $node->field_lesson_video[LANGUAGE_NONE][0]['fid'];
    $vediofile = file_load($vedioid);
    $vediourl = file_create_url($vediofile->uri);
    $class['dataurl']=$vediourl;
    $class['className']=$node->title;
    $class['teacherName']=$node->field_lesson_lecturer[LANGUAGE_NONE][0]['value'];
    $class['owner']=$node->field_lesson_owner[LANGUAGE_NONE][0]['value'];
    $class['classRoom']=$node->field_lesson_owner[LANGUAGE_NONE][0]['value'];
    $class['classRoom']=$node->field_lesson_place[LANGUAGE_NONE][0]['value'];
    $class['lessons']=$node->field_lesson_count_num[LANGUAGE_NONE][0]['value'];
    $class['classType']=$node->field_lesson_type[LANGUAGE_NONE][0]['value'];
    $class['info']=$node->field_lesson_info[LANGUAGE_NONE][0]['value'];
    return theme("detailclass_page", array(
        'detailClass' => $class,
        'classList'   => array(),
        'secondMenuNav' =>getSecondMenuNav('/danyClass/'),
    ));
}

function classes_detailteacher_page_callback($nid){
    $node=node_load($nid);
    $teacher['teacherName']=$node->title;
    $teacher['career']=$node->field_career[LANGUAGE_NONE][0]['value'];
    $teacher['info']=$node->field_teacher_info[LANGUAGE_NONE][0]['value'];
    $imgid = $node->field_lesson_pic[LANGUAGE_NONE][0]['fid'];
    $imgfile = file_load($imgid);
    $imageurl = file_create_url($imgfile->uri);
    $teacher['imgurl']=$imageurl;
    $refClassList=array();//dataurl,name,teacherName
    return theme("detailteacher_page",array(
        'teacher'   => $teacher,
        'refClassList'=> $refClassList,
        'secondMenuNav' =>getSecondMenuNav('/danyTeacher/'),
    ));
}

/**
 * Implements hook_theme()
 */
function classes_theme() {
    return array(
        'classes_page'  => array(
            'variables'=> array(),
            'template' => 'classes',
        ),
        'teachers_page' => array(
            'variables'=> array(),
            'template' => 'teachers',
        ),
        'campus_page'  => array(
            'variables'=> array(),
            'template' => 'campus',
        ),
        'admission_page' => array(
            'variables'=> array(),
            'template' => 'admission',
        ),
        'files_page'  => array(
            'variables'=> array(),
            'template' => 'files',
        ),
        'detailclass_page' => array(
            'variables'=> array(),
            'template' => 'detailclass',
        ),
        'detailteacher_page' => array(
            'variables'=> array(),
            'template' => 'detailteacher',
        ),
    );
}

function template_preprocess_classes_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    $classList=array();
    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query
    ->fields('n', array('nid'))
    ->condition('type', 'lesson')
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->addTag('node_access')
    ->execute()
    ->fetchCol();
    if (!empty($nids)) {
        $nodes = node_load_multiple($nids);
        foreach ($nodes as $key => $node) {
            $imgid = $node->field_lesson_pic[LANGUAGE_NONE][0]['fid'];
            $imgfile = file_load($imgid);
            $imageurl = file_create_url($imgfile->uri);
            $classList[]=array(
                'detailurl' => "?q=classes/detailclass/".$key,
                'imgurl'    => $imageurl,
                'title'     => $node->title,
                'teachername'=>$node->field_teacher_name[LANGUAGE_NONE][0]['value'],
                );
        }
    }
    $variables['classList']=$classList;
    $variables['imageLinkPathHead']=$module_path;
    $variables['secondMenuNav']=getSecondMenuNav('/danyClass/');
}

function template_preprocess_teachers_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    $variables['imageLinkPathHead']=$module_path;
    //测试使用的数据，应该从数据库获取
    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query
    ->fields('n', array('nid'))
    ->condition('type', 'teacher')
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->addTag('node_access')
    ->execute()
    ->fetchCol();
    if (!empty($nids)) {
        $nodes = node_load_multiple($nids);
        foreach ($nodes as $key => $node) {
            $imgid = $node->field_teacher_pic[LANGUAGE_NONE][0]['fid'];
            $imgfile = file_load($imgid);
            $imageurl = file_create_url($imgfile->uri);
            $teacherList[]=array(
                'detailurl' => "?q=classes/detailteacher/".$key,
                'imgurl'    => $imageurl,
                'teacherName'=> $node->title,
                'career'    => $node->field_career[LANGUAGE_NONE][0]['value'],   
                );
        }
    }
    //drupal_add_css($module_path.'/css/classes_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    //drupal_add_js($module_path.'/js/scripts.js');
    $variables['teacherList']=$teacherList;
    $variables['secondMenuNav']=getSecondMenuNav('/danyTeacher/');
}

function template_preprocess_campus_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    //drupal_add_css($module_path.'/css/classes_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    $pioneeringContext="";
    $baseFacilities="";
    $trainGuide="";
    $careerGuide="";
    $careerFinance="";
    
    $nid = variable_get('pioneeringContext', 44);
    $node = node_load($nid);
    if ($node) {
        $pioneeringContext = $node->body[LANGUAGE_NONE][0]['value'];
        $imgid = $node->field_image[LANGUAGE_NONE][0]['fid'];
        $imgfile = file_load($imgid);
        $imageurl = file_create_url($imgfile->uri);
    }
    $nid = variable_get('baseFacilities', 45);
    $node = node_load($nid);
    if ($node) {
        $baseFacilities = $node->body[LANGUAGE_NONE][0]['value'];
    }
    $nid = variable_get('trainGuide', 46);
    $node = node_load($nid);
    if ($node) {
        $trainGuide = $node->body[LANGUAGE_NONE][0]['value'];
    }
    $nid = variable_get('careerGuide', 47);
    $node = node_load($nid);
    if ($node) {
        $careerGuide = $node->body[LANGUAGE_NONE][0]['value'];
    }
    $nid = variable_get('baseFacilities', 48);
    $node = node_load($nid);
    if ($node) {
        $careerFinance = $node->body[LANGUAGE_NONE][0]['value'];
    }
    
    $variables['modulePath']=$module_path;
    $variables['pioneeringContext']=$pioneeringContext;
    $variables['baseFacilities']=$baseFacilities;
    $variables['trainGuide']=$trainGuide;
    $variables['careerGuide']=$careerGuide;
    $variables['careerFinance']=$careerFinance;
    $variables['imgurl']=$imageurl;
    $variables['secondMenuNav']=getSecondMenuNav('/danyCampus/');
}
function template_preprocess_admission_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    $variables['modulePath']=$module_path;
    
    // $build = array();
    // $query = db_select('node', 'n')->extend('PagerDefault');
    // $nids = $query
    // ->fields('n', array('nid'))
    // ->condition('type', 'article')
    // ->condition('status', 1)
    // ->condition('title',"招生信息")
    // ->orderBy('created', 'DESC')
    // ->limit(variable_get('default_nodes_main', 1))
    // ->addTag('node_access')
    // ->execute()
    // ->fetchCol();
    // if (!empty($nids)) {
    //     $nodes = node_load_multiple($nids);
    //     $admission=$nodes[$nids[0]]->body['und'][0]['value'];
    //     //$build += node_view_multiple($nodes);
    //     //$build['pager'] = array(
    //     //'#theme' => 'pager',
    //     //'#weight' => 5,
    //     //);
    // }
    $nid = variable_get('baseFacilities', 43);
    $node = node_load($nid);
    if ($node) {
        $admission = $node->body[LANGUAGE_NONE][0]['value'];
    }
    $variables['admission']=$admission;
    $variables['secondMenuNav']=getSecondMenuNav('/danyAdimission/');
}

function template_preprocess_files_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    //drupal_add_css($module_path.'/css/classes_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    $variables['modulePath']=$module_path;
    $variables['secondMenuNav']=getSecondMenuNav('/danyFiles/');
}


//util functin
function getSecondMenuNav($type)
{
    $nav='<nav class="w20" id="sideNav">
			<ul>
				<li class="danyClass">
					<a href="?q=classes/class">农业课堂</a>
				</li>
				<li class="danyTeacher">
					<a href="?q=classes/teachers">农业名师</a>
				</li>
				<li class="danyCampus">
					<a href="?q=classes/campus">创业园地</a>
				</li>
				<li class="danyAdmission">
					<a href="?q=classes/admission">招生信息</a>
				</li>
				<li class="danyFiles">
					<a href="?q=classes/files">资料下载</a>
				</li>
			</ul>
	</nav>';
    $html=preg_replace($type,"activeNavItem",$nav);
    return $html;
}