<?php
/**
 * Create by Visual Studio Code
 * Author : Dany
 * E-mail : ifeifei@stu.xmu.edu.cn
 * Data = 2016-04-16 16:16
 */
 
 /**
  * Implements hook_menu()
  */
function classes_menu(){
    $items['classes'] = array(
        'title' => '新农人培训',
        'page callback' => 'classes_class_page_callback',
        'access callback' => TRUE,
        'weight'=>30,
        'type' => MENU_SUGGESTED_ITEM,
        'menu_name' => 'main-menu',
    );
    $items['classes/class'] = array(
        'title' => t('农业课堂'),
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
    );
    $items['classes/teachers'] = array(
        'title' => t('农业名师'),
        'page callback' => 'classes_teacher_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    $items['classes/campus'] = array(
        'title' => t('创业园地'),
        'page callback' => 'classes_campus_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    $items['classes/admission'] = array(
        'title' => t('招生信息'),
        'page callback' => 'classes_admission_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    $items['classes/files'] = array(
        'title' => t('资料下载'),
        'page callback' => 'classes_files_page_callback',
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
    return $items;
}

/*
 * functions of page callback
 */
function classes_class_page_callback() {
    $module_path = drupal_get_path('module', 'classes');
    return theme("classes_page", array());
}

function classes_teacher_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("teachers_page", array());
}

function classes_campus_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("campus_page", array());
}

function classes_admission_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("admission_page", array());
}

function classes_files_page_callback(){
    $module_path = drupal_get_path('module', 'classes');
    return theme("files_page", array());
}

/**
 * Implements hook_theme()
 */
function classes_theme() {
    return array(
        'classes_page'  => array(
            'variables'=> array(),
            'template' => 'classes',
        ),
        'teachers_page' => array(
            'variables'=> array(),
            'template' => 'teachers',
        ),
        'campus_page'  => array(
            'variables'=> array(),
            'template' => 'campus',
        ),
        'admission_page' => array(
            'variables'=> array(),
            'template' => 'admission',
        ),
        'files_page'  => array(
            'variables'=> array(),
            'template' => 'files',
        ),
    );
}

function template_preprocess_classes_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    $variables['imageLinkPathHead']=$module_path;
    //测试使用的数据，应该从数据库获取
    foreach(range(0,4) as $value)
    {
        $productList[$value]=array(
        'imgurl'      => 'images/classes/class0'.($value+1).'.jpg',
        'externlink'  => url("teachers/{$node->nid}"),
        'productName' => 'productName1'.$value,
        'farmName'    => 'farmName1'.$value,
        'customers'   => $value,
        'comments'    => 'comments1.$value'
        );
    }
    //drupal_add_css($module_path.'/css/classes_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    //drupal_add_js($module_path.'/js/scripts.js');
    $variables['classList']=$productList;
}

function template_preprocess_teachers_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    $variables['imageLinkPathHead']=$module_path;
    //测试使用的数据，应该从数据库获取
    foreach(range(0,3) as $value)
    {
        $productList[$value]=array(
        'imgurl'      => 'images/teachers/teacher0'.($value+1).'.jpg',
        'teacherName' => '',
        'farmName'    => 'farmName1'.$value,
        'customers'   => $value,
        'comments'    => 'comments1.$value'
        );
    }
    //drupal_add_css($module_path.'/css/classes_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    //drupal_add_js($module_path.'/js/scripts.js');
    $variables['teacherList']=$productList;
}

function template_preprocess_campus_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    //drupal_add_css($module_path.'/css/classes_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    $pioneeringContext="";
    $baseFacilities="";
    $trainGuide="";
    $careerGuide="";
    $careerFinance="";
    
    $nid = variable_get('pioneeringContext', 44);
    $node = node_load($nid);
    if ($node) {
        $pioneeringContext = $node->body[LANGUAGE_NONE][0]['value'];
        $imgid = $node->field_image[LANGUAGE_NONE][0]['fid'];
        $imgfile = file_load($imgid);
        $imageurl = file_create_url($imgfile->uri);
    }
    $nid = variable_get('baseFacilities', 45);
    $node = node_load($nid);
    if ($node) {
        $baseFacilities = $node->body[LANGUAGE_NONE][0]['value'];
    }
    $nid = variable_get('trainGuide', 46);
    $node = node_load($nid);
    if ($node) {
        $trainGuide = $node->body[LANGUAGE_NONE][0]['value'];
    }
    $nid = variable_get('careerGuide', 47);
    $node = node_load($nid);
    if ($node) {
        $careerGuide = $node->body[LANGUAGE_NONE][0]['value'];
    }
    $nid = variable_get('baseFacilities', 48);
    $node = node_load($nid);
    if ($node) {
        $careerFinance = $node->body[LANGUAGE_NONE][0]['value'];
    }
    
    $variables['modulePath']=$module_path;
    $variables['pioneeringContext']=$pioneeringContext;
    $variables['baseFacilities']=$baseFacilities;
    $variables['trainGuide']=$trainGuide;
    $variables['careerGuide']=$careerGuide;
    $variables['careerFinance']=$careerFinance;
    $variables['imgurl']=$imageurl;
}
function template_preprocess_admission_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    $variables['modulePath']=$module_path;
    
    // $build = array();
    // $query = db_select('node', 'n')->extend('PagerDefault');
    // $nids = $query
    // ->fields('n', array('nid'))
    // ->condition('type', 'article')
    // ->condition('status', 1)
    // ->condition('title',"招生信息")
    // ->orderBy('created', 'DESC')
    // ->limit(variable_get('default_nodes_main', 1))
    // ->addTag('node_access')
    // ->execute()
    // ->fetchCol();
    // if (!empty($nids)) {
    //     $nodes = node_load_multiple($nids);
    //     $admission=$nodes[$nids[0]]->body['und'][0]['value'];
    //     //$build += node_view_multiple($nodes);
    //     //$build['pager'] = array(
    //     //'#theme' => 'pager',
    //     //'#weight' => 5,
    //     //);
    // }
    $nid = variable_get('baseFacilities', 43);
    $node = node_load($nid);
    if ($node) {
        $admission = $node->body[LANGUAGE_NONE][0]['value'];
    }
    $variables['admission']=$admission;
}

function template_preprocess_files_page(&$variables) {
    $module_path = drupal_get_path('module','classes');
    //drupal_add_css($module_path.'/css/classes_styles.css',array('group' => CSS_THEME, 'media' => 'all', 'weight' => 1));
    $variables['modulePath']=$module_path;
}