<?php

function admanage_menu() {
  $items = array();

  $items['admin/admanage'] = array(
    'title' => t('广告管理'),
    'description' => 'ads management page',
    'page callback' => 'admanage_page',
    'access callback' => true,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function admanage_page()
{

  $val=db_select('block_custom', 'b')
    ->fields('b')
    ->condition('info', '%' . db_like('广告') . '%', 'LIKE')
    ->execute();

  $index=0;

  foreach ($val as $key=>$block) {

    $rows[$index]['id']=$block->bid;
    $rows[$index]['pos']=$block->info;//l($node->title, 'node/' . $node->nid);
    $rows[$index]['image']="<div class='admanage-img'>".$block->body."</div>";
    $rows[$index]['link']=l('配置','admin/structure/block/manage/block/'.$block->bid.'/config');

    $index++;
  }

  $header=array(t('id'),t('广告位'),t('预览'),t('编辑'));
  $table = theme('table', array('header' => $header,'rows' => $rows ,'attributes' => array('class' => array('private-table'))));
  drupal_add_css(drupal_get_path('module', 'admanage') . '/admanage.css');

  return $table;
}