<?php
/**
 * @file
 * Create a block for friend recommendation
 * @author Wang Xiaoli (creator)
 */
function about_sidebar_left_menu()
{
    $items['aboutsidebarleftpage'] = array(
        'title' => '产业园基地左边栏',
        'page callback' => 'aboutsidebarleftpage_page_callback',
        'access callback' => TRUE,
        'type' => MENU_SUGGESTED_ITEM,
        'weight' => 1,
    );
    return $items;
}
function aboutsidebarleftpage_page_callback()
{
    return '';
}


/**
 * Implements hook_block_info().
 */
function about_sidebar_left_block_info()
{
    $blocks['about_sidebar_left'] = array(
        'info' => t('sidebar left of about'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['about_sidebar_left']['properties']['administrative'] = TRUE;

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function about_sidebar_left_block_view($delta = '',&$vars)
{
    $module_path = drupal_get_path('module', 'about_sidebar_left');
    if ($delta == 'about_sidebar_left') {
        $block = array();
        if (isset($vars['main_menu'])) {
        	$sql = "SELECT m.load_functions, m.to_arg_functions, m.access_callback, m.access_arguments, m.page_callback, m.page_arguments, m.delivery_callback, m.title, m.title_callback, m.title_arguments, m.type, m.description, ml.*
    				FROM {menu_links} ml LEFT JOIN {menu_router} m ON m.path = ml.router_path
    				WHERE ml.menu_name = :menu
    				ORDER BY p1 ASC, p2 ASC, p3 ASC, p4 ASC, p5 ASC, p6 ASC, p7 ASC, p8 ASC, p9 ASC";
        	$result = db_query($sql, array(':menu' => 'main-menu'), array('fetch' => PDO::FETCH_ASSOC));
        	$links = array();
        	foreach ($result as $item) {
        		$links[] = $item;
        	}
        }
        $tree = menu_tree_data($links);
        $menu_links='<nav id="sideNav" class="w20"><ul>';
        foreach ($tree as $menu_item) {
        	if(!empty($menu_item['link']['title'])) {
        		$sublink = $menu_item['below'];
        		foreach ($sublink as $sublinkitem) {
        			$menu_links .= '<li><a href="?q=' . $sublinkitem['link']['link_path'] . '">' . $sublinkitem['link']['title'] . '</a></li>';
        		}
        	}
        }
        $menu_links.='</ul>';
        $block['content'] = $menu_links;
        return $block;
    }
}
