<?php
/**
 * Created by PhpStorm.
 * User: yunjia
 * Date: 2016/3/16
 * Time: 16:18
 */

/**
 * Implements hook_menu().
 */
function training_menu()
{
    $items['productbox'] = array(
        'title' => t('Product Admin'),
        'page callback' => 'product_admin_page_callback',
       'access arguments' => array('access content'),
       'type' => MENU_SUGGESTED_ITEM,
        'file' => 'training.pages.inc',
    );

    return $items;
}