<?php
/**
 * Created by PhpStorm.
 * User: yunjia
 * Date: 2016/3/29
 * Time: 16:18
 */

/**
 * Implements hook_menu().
 */
function goodsShelf_menu()
{
    $items['admin/goodsshelf'] = array(
        'title' => t('货架管理'),
        'page callback' => 'goods_shelf_callback',
        'access callback' => TRUE, //访问权限，设为TRUE的话任何人都能访问
        'access arguments' => '',
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'goodsShelf.pages.inc',
    );

    return $items;
}