<?php
/**
 * @file
 * Create a block for friend recommendation
 * @author Wang Xiaoli (creator)
 */

function home_content_enable()
{
    variable_set('site_frontpage', 'homepage');
}

function home_content_menu()
{
    $items['homepage'] = array(
        'title' => '首页',
        'page callback' => 'homepage_page_callback',
        'access callback' => TRUE,
        'type' => MENU_SUGGESTED_ITEM,
        'weight' => 1,
    );
    return $items;
}

function homepage_page_callback()
{
    return '';
}

/**
 * Implements hook_block_info().
 */
function home_content_block_info()
{
    $blocks['home_content'] = array(
        'info' => t('Home Content'),
        'cache' => DRUPAL_NO_CACHE,//TODO 不起作用
        'status' => 1,
        'weight' => 0,
        'region' => 'Content',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => true,
    );
    $blocks['home_content']['properties']['administrative'] = TRUE;

    $blocks['home_highlighted'] = array(
        'info' => t('home highlighted'),
        'cache' => DRUPAL_NO_CACHE,
        'status' => 1,
        'weight' => 0,
        'region' => 'Highlighted',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => true,
    );
    $blocks['home_highlighted']['properties']['administrative'] = TRUE;

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function home_content_block_view($delta = '')
{
    $module_path = drupal_get_path('module', 'home_content');
    if ($delta == 'home_content') {
        $block = array();
        //========================================
        //此处js需要修改
        //待解决的问题search_form 未修改
        //========================================
        $html = <<<EOS
        <div class="slider" data-i="0">
			<div class="controls">
				<div class="bulletNav">
						<div class="bullet" name="bullet" data-i="0" style="background-color: #68b7fd" onClick="slide(this.parentNode.parentNode.parentNode, this.dataset.i)"></div>
						<div class="bullet" name="bullet" data-i="1" onClick="slide(this.parentNode.parentNode.parentNode, this.dataset.i)"></div>
						<div class="bullet" name="bullet" data-i="2" onClick="slide(this.parentNode.parentNode.parentNode, this.dataset.i)"></div>
						<div class="bullet" name="bullet" data-i="3" onClick="slide(this.parentNode.parentNode.parentNode, this.dataset.i)"></div>
						<div class="bullet" name="bullet" data-i="4" onClick="slide(this.parentNode.parentNode.parentNode, this.dataset.i)"></div>
				</div>
				<div class="arrowNav">
					<div class="arrowLeft" onClick="slide(this.parentNode.parentNode.parentNode, parseInt(this.parentNode.parentNode.parentNode.dataset.i)-1)">
					</div>
					<div class="arrowRight" onClick="slide(this.parentNode.parentNode.parentNode, parseInt(this.parentNode.parentNode.parentNode.dataset.i)+1)">
					</div>
				</div>
			</div>
			<div class="slide" data-i="0">
				<img src="$module_path/images/slider/0.jpg"/>
			</div>
			<div class="slide" data-i="1" style="display: none">
				<img src="$module_path/images/slider/1.jpg"/>
			</div>
			<div class="slide" data-i="2" style="display: none">
				<img src="$module_path/images/slider/2.jpg"/>
			</div>
			<div class="slide" data-i="3" style="display: none">
				<img src="$module_path/images/slider/3.jpg"/>
			</div>
			<div class="slide" data-i="4" style="display: none">
				<img src="$module_path/images/slider/4.jpg"/>
			</div>
		</div> 
EOS;
        $block['content'] = $html;
        return $block;
    } else if ($delta == 'home_highlighted') {
        $block = array();
        $newsurl=url('news');
        $farmshowurl=url('farmshow');
        $productsurl=url('farmshow/product');
        $classesurl=url('classes');
        $forumurl=url('forum');
        
        $html =<<<EOS
        <nav class="homenav">
		<a href="$newsurl">
            <div class="bigbutton blue">
				<div class="iconArea">
					<img alt="news" src="$module_path/images/icons/news.png">
				</div>
				<h2>活动报道</h2>
			</div>
		</a>
		<a href="$farmshowurl">
            <div class="bigbutton green">
				<div class="iconArea">
					<img alt="farms" src="$module_path/images/icons/farms.png">
				</div>
				<h2>农场信息</h2>
			</div>
		</a>
		<a href="$productsurl">
			<div class="bigbutton orange">
				<div class="iconArea">
					<img alt="products" src="$module_path/images/icons/products.png">
				</div>
				<h2>农产品信息</h2>
			</div>
		</a>
		<a href="$classesurl">
			<div class="bigbutton red">
				<div class="iconArea">
					<img alt="training" src="$module_path/images/icons/training.png">
				</div>
				<h2>培训方案</h2>
			</div>
		</a>
		<a href="$forumurl">
			<div class="bigbutton purple">
				<div class="iconArea">
					<img alt="bbs" src="$module_path/images/icons/forum.png">
				</div>
				<h2>讨论区</h2>
			</div>
		</a>
	</nav>
EOS;
        $block['content'] = $html;
        return $block;
    }
}
