<?php
/**
 * @file
 * Create a block for friend recommendation
 * @author Wang Xiaoli (creator)
 */

/**
 * Implements hook_block_info().
 */
function home_content_block_info()
{
    $blocks['home content'] = array(
        'info' => t('home content'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['home_content']['properties']['administrative'] = TRUE;

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function home_content_block_view($delta = '')
{
    $module_path = drupal_get_path('module', 'home_content');
    $block = array();
    $html = '<div id="slider">
		<img id="sliderImg" src="'.$module_path.'/images/2.jpg" alt="slider"/>
	</div>';
//    $block['subject'] = t('home content');
    $block['content'] = $html;
    return $block;
}
