<?php
/**
 * Created by IntelliJ IDEA.
 * User: Sadako
 * Date: 2016/4/15
 * Time: 17:40
 */

/**
 * Implements hook_menu().
 */
function about_menu() {
    $items['about'] = array(
        'title' => t('About'),
        //'page callback' => 'about_course_page_callback',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'menu_name' => 'main-menu',
    );
//    $items['about/courses'] = array(
//        'title' => t('Courses'),
//        'type' => MENU_DEFAULT_LOCAL_TASK,
//    );
//    $items['about/teachers'] = array(
//        'title' => t('Teachers'),
//        'page callback' => 'about_teacher_page_callback',
//        'access callback' => TRUE,
//        'type' => MENU_LOCAL_TASK,
//        'weight' => 5,
//    );
    return $items;
}

//function about_course_page_callback() {
//    $module_path = drupal_get_path('module', 'about');
//    drupal_add_css($module_path . '/css/about.css');
//    // drupal_add_js();
//    return theme("courses_page", array('imglink' => 'http://img.png'));
//}
//
//function about_teacher_page_callback() {
//    return "Hello world1";
//}

/**
 * Implements hook_theme()
 */
function about_theme() {
    return array(
        'courses_page' => array(
            'variables' => array('imglink' => NULL),
            'template' => 'courses',
        ),
    );
}

/**
 * Processes variables for member-page.tpl.php.
 *
 * @param $variables
 *   An associative array containing the following key:
 *   - link
 *   - content
 *
 * @see courses.tpl.php
 */
//function template_preprocess_courses_page(&$variables) {
//    $variables['imglink'] = 'http://img.png';
//}