<?php
/**
 * Created by PhpStorm.
 * User: yunjia
 * Date: 2016/3/27
 * Time: 16:18
 */

/**
 * Implements hook_menu().
 */
function goodsInfo_menu()
{
    $items['goodsinfo/%'] = array(
        'title' => t('产品详细信息'),
        'page callback' => 'goods_show_form',
        'page arguments' => array(1),
        'access callback' => TRUE, //访问权限，设为TRUE的话任何人都能访问
        'access arguments' => '',
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'goodsInfo.pages.inc',
    );

    return $items;
}