<?php
/**
 * Created by PhpStorm.
 * User: yunjia
 * Date: 2016/4/16
 * Time: 16:18
 */

/**
 * Implements hook_node_info()
 * Create the farm node.
 */
function farm_node_info(){
    return array(
        'farm'=>array(
            'name' => t('farm'),
            'module' => 'farm',
            'base' => 'node_content',
            'description' => 'the farm node type for the company',
            'has_title' => TRUE,
            'has_body' => TRUE
        )
    );
}


/**
 * Implements hook_menu().
 */
function farm_menu()
{
    $items['admin/farm'] = array(
        'title' => t('农场管理'),
        'description' => '对站点中的农场进行管理,进行增加、编辑、删除等操作',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('farm_admin_content'),
        'access arguments' => array('access content overview'),
        'file' => 'farm_admin.pages.inc',
    );

    $items['admin/farm/add'] = array(
        'title' => '添加农场',
        'title callback' => 'check_plain',
        'page callback' => 'farm_add',
        'access callback' => 'node_access',
        'access arguments' => array('create', 'farm'),
        'type' => MENU_LOCAL_ACTION,
        'file' => 'farm_admin.pages.inc',
    );

    $items['admin/farm/%node'] = array(
        'title' => t('farm product'),
        'page callback' => 'farm_product_page',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'file' => 'farm_product_admin.pages.inc',
    );

    $items['admin/farm/%/add'] = array(
        'title' => '添加产品',
        'title callback' => 'check_plain',
        'page callback' => 'farm_product_add',
        'page arguments' => array(2),
        'access callback' => 'node_access',
        'access arguments' => array('create', 'product'),
        'type' => MENU_LOCAL_ACTION,
        'file' => 'farm_product_admin.pages.inc',
    );

    //farm-front
    $items['farmshow'] = array(
        'title' => t('农业展馆'),
        'page callback' => 'farmshow_leisurefarm_page_callback',
        'access callback' => TRUE,
        'type' => MENU_SUGGESTED_ITEM,
        'menu_name'=>'main-menu',
        'weight'=>40,
    );
    $items['farmshow/farm'] = array(
        'title' => t('休闲农庄'),
        'access callback' => TRUE,
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['farm/%'] = array(
        'title' => t('farm'),
        'page callback' => 'farm_page_callback',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
    );
    $items['farms'] = array(
        'title' => t('farms'),
        'page callback' => 'farms_page_callback',
        'access arguments' => array('access content'),
    );

    return $items;
}

/**
 * @param $fid 农场的nid
 * @return 农场详细信息页面
 */
function farm_page_callback($fid){
    $farm = node_load($fid);
    //查找出农场图片
    $farm_image_uri = $farm->field_farm_image[LANGUAGE_NONE][1]['uri'];
    //$farm_image_locate = explode('//', $farm_image_uri);
    //$farm_image_filepath = $GLOBALS['base_url'].'/sites/default/files/' . $farm_image_locate[1];
    $farm_image_filepath =file_create_url($farm_image_uri);
    $build ="<main>
		    <nav id='sideNav' class='w20'>
			<ul>
				<li class='activeNavItem'> <a href='".url("farmshow/farm")."'>休闲农庄</a> </li>
				<li > <a href='".url("farmshow/product")."'>农业展品</a> </li>
			</ul>
		</nav>";
    $build .="<section class='w80'>
			<div class='bar'>
                <img class='icon' src='".$GLOBALS['base_url']."/sites/all/themes/xinxin_front/images/icons/farms_icon.png'>
				<h1><a class='underline' href='".url("farmshow/farm")."'>休闲农庄</a> >".$farm->title."</h1></div>
			<img src=".$farm_image_filepath." alt='Jackie Chan' class='alignCenter w100'/>
		</section>";
    $build .="<section class='w80'>
			<div class='bar w100'>
				<h3>".( (isset($farm->field_farm_location[LANGUAGE_NONE]) && isset($farm->field_farm_location[LANGUAGE_NONE][0])) ? $farm->field_farm_location[LANGUAGE_NONE][0]['value'] : '' )."</h3>
				<div class='floatRight alignRight'> <a href='#' class='favLink'>加入收藏</a></div>
			</div>
			<div class='w100'>
				<p>".( (isset($farm->body[LANGUAGE_NONE]) && isset($farm->body[LANGUAGE_NONE][0])) ? $farm->body[LANGUAGE_NONE][0]['value'] : '' )."</p>
				<h2>联系方式</h2>
                <h3>".( (isset($farm->field_farm_telephone[LANGUAGE_NONE]) && isset($farm->field_farm_telephone[LANGUAGE_NONE][0])) ? $farm->field_farm_telephone[LANGUAGE_NONE][0]['value'] : '' )."</h3>
			</div>
			</section>";
    $build .="<section class='w80'>
			<div class='bar'>
				<h2>相关产品</h2>
			</div>";
    //查询出此农场中的产品
    $query = db_select('field_data_field_product_farm', 'f')->extend('PagerDefault');
    $pids = $query
        ->fields('f', array('entity_id'))
        ->condition('f.field_product_farm_value', $farm->nid)
        ->orderBy('entity_id', 'DESC')
        ->limit(4)
        ->execute()
        ->fetchCol();
    $products = node_load_multiple($pids);
    foreach($products as $key => $product) {
        //查询产品的类型
        $myfield_array = field_get_items('node', $product,'field_product_type');
        $myfield = isset($myfield_array[0]) ? $myfield_array[0] :'';
        if (!empty($myfield)) {
            $tid = $myfield['tid'];
            $product_type = taxonomy_term_load($tid);//使用API函数查找出类型

            //获取产品图片
            $myfield_array = field_get_items('node', $product, 'field_product_photo');
            $image = isset($myfield_array[0]) ? $myfield_array[0] : '';
            $product_image_filepath = file_create_url($image['uri']);
            $build .="<div class='block1'> <span class='fav'>收藏</span> <img src=".$product_image_filepath." />
                    <a href='".url("product/{$product->nid}") . "'><h3 class='product_title'>".$product->title."</h3></a>
                    <p class='product_price'><span class='farmName'>产品类型：".check_plain($product_type->name)."</span><span class='floatRight'>".$product->field_product_price[LANGUAGE_NONE][0]['value']."</span><span class='floatRight'>￥</span></p>
                </div>";
        }
    }
    $build .="</main>";
    return $build;
}

/**
 * @return 休闲农庄页面
 */
function farmshow_leisurefarm_page_callback(){
    return theme('farm_page',array());
}

/**
 * @return 所有农庄页面
 */
function farms_page_callback(){
    return theme('farms_page',array());
}

/**
 * @return array
 */
function farm_theme(){
    return array(
        'farm_page'=>array(
            'variables'=> array('title'=>'推荐农庄'),
            'template' => 'farm',
        ),
        'farms_page'=>array(
            'variables'=> array('title'=>'休闲农庄'),
            'template' => 'farm',
        ),
    );
}

/**
 * 推荐农庄总览页面
 * @param $variables
 */
function template_preprocess_farm_page(&$variables){
    $variables['farm_page']=url("farmshow/farm");
    $variables['product_page']=url("farmshow/product");

    $build = "";
    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query
        ->fields('n', array('nid', 'created'))
        ->condition('type', 'farm')
        ->condition('status', 1)
        ->orderBy('created', 'DESC')
        ->limit(variable_get('default_nodes_main', 10))
        ->execute()
        ->fetchCol();

    if (!empty($nids)) {
        $nodes = node_load_multiple($nids);
    }

    foreach($nodes as $key=>$value){
        //查找出农场图片
        $farm_image_filepath = isset($value->field_farm_image[LANGUAGE_NONE]) && isset($value->field_farm_image[LANGUAGE_NONE][0]) ? file_create_url($value->field_farm_image[LANGUAGE_NONE][0]['uri']) : '';

        //查询出此农场中的产品
        $query = db_select('field_data_field_product_farm', 'f')->extend('PagerDefault');
        $pids = $query
            ->fields('f', array('entity_id'))
            ->condition('f.field_product_farm_value', $value->nid)
            ->orderBy('entity_id', 'DESC')
            ->limit(10)
            ->execute()
            ->fetchCol();
        $products = node_load_multiple($pids);
        $product_images = array();
        $count = 0;
        foreach($products as $key => $product) {
            if($count==4){
                break;
            }
            //获取产品图片
            $myfield_array = field_get_items('node', $product, 'field_product_photo');
            $image = isset($myfield_array[0]) ? $myfield_array[0] : '';
            if (!empty($image)) {
                $product_images[$key] = file_create_url($image['uri']);
                $count++;
            }
        }
        $build .= '<a href="'.url("farm/{$value->nid}") . '">';
        $build .= "<div class='wideBlock'>";
        $build .= "<div class='blockTitle'><h2>".$value->title."</h2><br/>
                <h3>地址：". ( ( isset($value->field_farm_location[LANGUAGE_NONE]) && isset($value->field_farm_location[LANGUAGE_NONE][0]) ) ? $value->field_farm_location[LANGUAGE_NONE][0]['value'] : '' ) ."</h3></div>";
        $build .="<img src='".$farm_image_filepath."' class='w40 floatLeft'/>";
        $build .="<div class='blockInformation w60 floatLeft'>
                <p class='alignRight'><a href='#' class=''>加入收藏</p></a>";
        $build .="<p>". ( ( isset($value->body[LANGUAGE_NONE]) && isset($value->body[LANGUAGE_NONE][0]) ) ? $value->body[LANGUAGE_NONE][0]['value'] : '' ) ."</p>";
        $build .="<p class='alignRight'><a href='". url("farm/{$value->nid}") ."'>详细信息 ></a></p>" ;
        $build .="<div class='alignRight products'>";
        foreach($product_images as $value){
            $build .= "<img src=".$value.">";
        }
        $build .="</div></div></div></a>";
    }
    $variables['content'] = $build;

    $build_search = "<div class='bar'>
                    <img class='icon' src='".$GLOBALS['base_url']."/sites/all/themes/xinxin_front/images/icons/farms_icon.png'>
                    <h1>休闲农庄</h1>
                    <div class='search floatRight'><a href='#'><img src=".$GLOBALS['base_url']."/sites/all/themes/xinxin_front/images/icons/search_bar.png alt='search'></a><input type='text' name='search'></div>
                    <div class='button floatRight'><a href='". url("farms") . "'>+</a></div>
                    </div>";
    $variables['search'] = $build_search;
}

/**
 * 所有农庄展示页面
 * @return 页面数据
 */
function template_preprocess_farms_page(&$variables){
    $build_search = "<div class='bar'><img class='icon' src='".$GLOBALS['base_url']."/sites/all/themes/xinxin_front/images/icons/farms_icon.png'><h1>休闲农庄</h1>
                    <div class='search floatRight'><a href='#'><img src=".$GLOBALS['base_url']."/sites/all/themes/xinxin_front/images/icons/search_bar.png alt='search'></a><input type='text' name='search'></div>
                    <div class='button floatRight'><a href='".url("farmshow/farm")."'>+</a></div>
                    </div>";
    $build = "";
    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query
        ->fields('n', array('nid', 'created'))
        ->condition('type', 'farm')
        ->condition('status', 1)
        ->orderBy('created', 'DESC')
        ->limit(variable_get('default_nodes_main', 10))
        ->execute()
        ->fetchCol();

    if (!empty($nids)) {
        $nodes = node_load_multiple($nids);
    }
    foreach($nodes as $key=>$value){
        //查找出农场图片
        $farm_image_uri = ( isset($value->field_farm_image[LANGUAGE_NONE]) && isset($value->field_farm_image[LANGUAGE_NONE][0]) ) ? $value->field_farm_image[LANGUAGE_NONE][0]['uri'] : '';
//        $farm_image_locate = explode('//', $farm_image_uri);
//        $farm_image_filepath = $GLOBALS['base_url'].'/sites/default/files/' . $farm_image_locate[1];

        $build .="<a href='". url("farm/{$value->nid}")."'>
			<div class='block1'>
				<span class='fav'>收藏</span> <img src='".file_create_url($farm_image_uri)."'/>
				<h3>".$value->title."</h3>
				<p><span class='farmName'>地点：". ( ( isset($value->field_farm_location[LANGUAGE_NONE]) && isset($value->field_farm_location[LANGUAGE_NONE][0]) ) ? $value->field_farm_location[LANGUAGE_NONE][0]['value'] : '') ."</span><span class='floatRight'>&gt;</span><span class='floatRight'>详细信息</span></p>
			</div>
            </a>";

    }
    $variables['search'] = $build_search;
    $variables['content'] = $build;
}