<?php
/**
 * Created by apple
 * User: yuyao
 * Date: 2016/4/23
 * Time: 17:32
 */

 /**
 * Implements hook_menu().
 */
 function member_menu()
 {
 	//member-front
 	$items['membercenter'] = array(
 		'title' => '会员中心',
 		'access callback' => TRUE,
 		'type' => MENU_SUGGESTED_ITEM,
 		'menu_name'=>'main-menu',
        'weight'=>0,
 		'page callback' => 'member_call_back',
 	);
    return $items;
}

function member_call_back() {
	if(user_is_logged_in()) {
		global $user;
		if (in_array('企业会员', $user->roles)) {
			return memberCompany_call_back();
		}
		else {
			return memberIndividual_call_back();
		}
	}
	else {
		drupal_goto('user/login',  array('query'=>drupal_get_destination()));
	}
}

function memberIndividual_call_back()
{
    global $user;
    global $base_url;
    $imgthumbnailurl = path_to_theme() . '/images/users/user0.jpg';
    if( isset($user->picture) && is_object($user->picture) ) {
        $imgfile = $user->picture;
        $file_path = file_unmanaged_copy($imgfile->uri);
        $imgthumbnailurl = image_style_url('thumbnail', $file_path) ? $file_path : $imgthumbnailurl;
    }

    //0 for male and 1 for female
    //$sex = ( isset($user->sex) && isset($user->sex[LANGUAGE_NONE]) ) ? $user->sex[LANGUAGE_NONE][0]['value'] : '';
    //$company = ( isset($user->personal_company) && isset($user->personal_company[LANGUAGE_NONE]) ) ? $user->personal_company[LANGUAGE_NONE][0]['value'] : '';
    //$real_name = ( isset($user->real_name) && isset($user->real_name[LANGUAGE_NONE]) ) ? $user->real_name[LANGUAGE_NONE][0]['value'] : '';
    //user register location
    //$register_location = ( isset($user->field_user_location) && isset($user->field_user_location[LANGUAGE_NONE]) ) ? $user->field_user_location[LANGUAGE_NONE][0]['value'] : '';
    
    //0 for male and 1 for female
    $sex_1 = db_select('field_data_field_sex', 'f')
        ->fields('f', array('field_sex_value'))
        ->condition('f.entity_id', $user->uid)
        ->execute()
        ->fetchCol();

    $company_1 = db_select('field_data_field_personal_company', 'f')
        ->fields('f', array('field_personal_company_value'))
        ->condition('f.entity_id', $user->uid)
        ->execute()
        ->fetchCol();

    $real_name_1 = db_select('field_data_field_real_name','f')
        ->fields('f', array('field_real_name_value'))
        ->condition('f.entity_id', $user->uid)
        ->execute()
        ->fetchCol();
        
    $register_location_1 = db_select('field_data_field_user_location','f')
        ->fields('f', array('field_user_location_value'))
        ->condition('f.entity_id', $user->uid)
        ->execute()
        ->fetchCol();
        
    $sex =  isset($sex_1) ? $sex_1[0] : '';
    $company =  isset($company_1) ? $company_1[0] : '';
    $real_name =  isset($real_name_1) ? $real_name_1[0] : '';
    $register_location =  isset($register_location_1) ? $register_location_1[0] : '';
    
    if($sex==0)
        $sex_value='男';
    else
        $sex_value='女';
 
    
    $membercenter_url = url('membercenter');
    $collection_url = url("mycollection");
    $friend_circle_url = url("user/".$user->uid."/relationships");
    
    $build =<<<EOS
    <main id='mainSection'>
        <nav class="w20" id="sideNav">
            <ul>
                <li class="activeNavItem">
                    <a href="$membercenter_url">我的信息</a>
                </li>
                <li>
                    <a href="$collection_url">我的收藏</a>
                </li>               
                <li>
                    <a href="$friend_circle_url">我的朋友圈</a>
                </li>
            </ul>
        </nav>
        <section class='w80'>
            <div class='bar'>
                <img class="icon" src="$base_url/sites/all/themes/xinxin_front/images/icons/member_icon.png"/>
                <h1>我的信息</h1>
                <a class='floatRight' href="$base_url?q=/user/$user->uid/edit">修改信息 &gt;</a>
            </div>
            <div class='profilePicture floatLeft alignCenter w25'>
                <img class='w100' src="$imgthumbnailurl">
            </div>
            <div class='w75 paddingLeft paddingRight floatLeft'>
                <table class='personalInfo w100'>
                    <tr>
                        <td>昵称</td>
                        <td class='alignRight'>$user->name</td>
                    </tr>
                    <tr>
                        <td>真实姓名</td>
                        <td class="alignRight">$real_name</td>
                    </tr>
                    <tr>
                        <td>性别</td>
                        <td class="alignRight">$sex_value</td>
                    </tr>
                    <tr>
                        <td>所属公司</td>
                        <td class="alignRight">$company</td>
                    </tr>
                    <tr>
                        <td>电子邮件</td>
                        <td class='alignRight'>$user->mail</td>
                    </tr>
                    <tr>
                        <td>注册地点</td>
                        <td class='alignRight'>$register_location</td>
                    </tr>
                </table>
            </div>
        </section>
    </main>
EOS;
    return $build;
}

function memberCompany_call_back()
{
    global $user;
    global $base_url;
    $imgthumbnailurl = path_to_theme() . '/images/users/company0.jpg';
    if( isset($user->picture) && is_object($user->picture) ) {
        $imgfile = $user->picture;
        $file_path = file_unmanaged_copy($imgfile->uri);
        $imgthumbnailurl = image_style_url('thumbnail', $file_path) ? $file_path : $imgthumbnailurl;
    }
    
    $tel_1 = db_select('field_data_field_user_tel', 'f')
        ->fields('f', array('field_user_tel_value'))
        ->condition('f.entity_id', $user->uid)
        ->execute()
        ->fetchCol();

    $address_1 = db_select('field_data_field_address','f')
        ->fields('f', array('field_address_value'))
        ->condition('f.entity_id', $user->uid)
        ->execute()
        ->fetchCol();
        
    $register_location_1 = db_select('field_data_field_user_location','f')
        ->fields('f', array('field_user_location_value'))
        ->condition('f.entity_id', $user->uid)
        ->execute()
        ->fetchCol();
        
    $tel =  isset($tel_1) ? $tel_1[0] : '';
    $address =  isset($address_1) ? $address_1[0] : '';
    $register_location =  isset($register_location_1) ? $register_location_1[0] : '';
    
    
    //user register location
    //$register_location = ( isset($user->field_user_location) && isset($user->user_location[LANGUAGE_NONE]) ) ? $user->user_location[LANGUAGE_NONE][0]['value'] : '';
    //$tel = ( isset($user->field_user_tel) && isset($user->field_user_tel[LANGUAGE_NONE]) ) ? $user->field_user_tel[LANGUAGE_NONE][0]['value'] : '';
    //$address = ( isset($user->address) && isset($user->address[LANGUAGE_NONE]) ) ? $user->address[LANGUAGE_NONE][0]['value'] : '';
    /*$tel = $user->field_user_tel[LANGUAGE_NONE][0]['value'];
    $address = $user->field_address[LANGUAGE_NONE][0]['value'];*/
    
    $adform_array = drupal_get_form('advertistment_form');
    $adform = drupal_render($adform_array);
    $collection_url = url("mycollection");
    $membercenter_url = url('membercenter');
    
    $build =<<<EOS
    <main id="mainSection">
        <nav class="w20" id="sideNav">
            <ul>
                <li class="activeNavItem">
                    <a href="$membercenter_url">我的信息</a>
                </li>
                <li>
                    <a href="$collection_url">我的收藏</a>
                </li>
            </ul>
        </nav>
        <section class="w80">
            <div class="bar">
                <img class="icon" src="$base_url/sites/all/themes/xinxin_front/images/icons/member_icon.png"/>
                <h1>企业会员</h1>
                <a class='floatRight' href="$base_url?q=/user/$user->uid/edit">修改信息 &gt;</a>
            </div>
            <div class="profilePicture floatLeft w100">
                <img class='w100' src="$imgthumbnailurl">
            </div>
            <div class="w100 floatLeft">
                <table class="personalInfo w100">
                    <tr>
                        <td>公司名称</td>
                        <td class="alignRight">$user->name</td>
                    </tr>
                    <tr>
                        <td>地址</td>
                        <td class="alignRight">$address</td>
                    </tr>
                    <tr>
                        <td>联系方式</td>
                        <td class="alignRight">$tel</td>
                    </tr>
                    <tr>
                        <td>电子邮件</td>
                        <td class="alignRight">$user->mail</td>
                    </tr>
                    <tr>
                        <td>注册地点</td>
                        <td class='alignRight'>$register_location</td>
                    </tr>
                </table>
                <br>
            </div>
            </section>
            <section class="w80">
                <div class="bar">
                    <h1>广告申请</h1>
                </div>
                $adform
            </div>
            </section>

    </main>
EOS;
    return $build;
    //申请链接待修改
    //上传文件待修改
}


function advertistment_form($form, &$form_state){

    $form['#attributes']['enctype'] = 'multipart/form-data';

    $form['adimage'] = array(
        '#type' => 'file',
        '#title' => t('广告图片'),
        '#size' => 48,
    );

    $form['adlink'] = array(
        '#type' => 'textfield',
        '#title' => t('广告链接'),
        '#size' => 48,
    );

    $form['adposition'] = array(
        '#type' => 'textfield',
        '#title' => t('广告位置'),
        '#description' => t('请填写你要放置广告的页面的链接，如：Xinxin/farmshow'),
        '#size' => 48,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('申请'),
    );
    return $form;

    /*<form class="alignCenter" >
                <table>
                    <tr>
                        <td>
                            <label class="alignLeft" for="image">广告图片</label>
                        </td>
                        <td>
                            <input type="file" name="image">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="alignLeft" for="website">广告链接</label>
                        </td>
                        <td>
                            <input type="text" name="link">
                        </td>
                    </tr>
                </table>
                <div class="button">
                    <a href="#">申请</a>
                </div>
                </form>*/
}

/**
 * 广告位申请待完善
 * @param $form
 * @param $form_state
 * @return mixed
 */
function advertistment_form_submit($form, $form_state){
    if(form_get_errors())
        return $form;

    $validators = array();
    $dest = "public://pictures/admange";
    $file = file_save_upload('adimage', $validators, $dest,$replace = FILE_EXISTS_RENAME);
    if ($file) {
        //$admageurl = image_style_url('thumbnail', $file->uri) ? $file->uri : '';
        $base_locate = $GLOBALS['base_url'];
        $base_url = explode('/', $base_locate);
        $admage_locate = explode('//', $file->uri);
        $admage_filepath = '/'.$base_url[3].'/'.variable_get('file_' . file_default_scheme() . '_path', conf_path() . '/files').'/'. $admage_locate[1];
    }
    else {
        watchdog('file', 'The file upload failed. %upload', array('%upload' => 'adimage'));
        form_set_error('advertistment_form', t("上传图片失败"));
    }

    global $user;

    $time = date('y-m-d h:i:s',time());
    $delta = db_insert('block_custom')
        ->fields(array(
            'body' => "<p><img alt='' src='".$admage_filepath."' width='1920' /></p>",
            'info' => $user->name.$time."申请的广告",
            'format' => "full_html",
        ))
        ->execute();
    // Store block delta to allow other modules to work with new block.
    $form_state['values']['delta'] = $delta;

    $query = db_insert('block')->fields(array('visibility', 'pages', 'custom', 'title', 'module', 'theme', 'status', 'weight', 'delta', 'cache'));
    foreach (list_themes() as $key => $theme) {
        if ($theme->status) {
            $query->values(array(
                'visibility' => 1,
                'pages' => '',
                'custom' => 0,
                'title' => '',
                'module' => 'block',
                'theme' => $theme->name,
                'status' => 0,
                'weight' => 0,
                'delta' => $delta,
                'cache' => DRUPAL_NO_CACHE,
            ));
        }
    }
    $query->execute();

    $val=db_select('block_custom', 'b')
        ->fields('b')
        ->condition('info', $user->name.$time.'申请的广告')
        ->execute();

    //存入数据库，广告位申请内容类型
    $nodeuri = array(
        'title' =>$user->name.$time."申请的广告",
        'type'=> 'advertising_application',
        'uid'=>$user->uid,
        'field_ad_appl_uid'=>array(
            'und'=>array(
                0=>array(
                    'value'=>$user->uid
                )
            )
        ),
        'field_ad_block_id'=>array(
            'und'=>array(
                0=>array(
                    'value'=>$delta
                )
            )
        ),
    );
    node_save((object)$nodeuri);

    return $form;
}




