<?php
/**
 * @file
 * Create a block for friend recommendation
 * @author Wang Xiaoli (creator)
 */
function login_menu()
{
    $items['loginpage'] = array(
        'title' => '登录',
        'page callback' => 'loginpage_page_callback',
        'access callback' => TRUE,
        'type' => MENU_SUGGESTED_ITEM,
        'weight' => 1,
    );
    return $items;
}

function loginpage_page_callback()
{
    return '';
}

/**
 * Implements hook_block_info().
 */
function login_block_info()
{
    $blocks['login'] = array(
        'info' => t('login'),
        'cache' => DRUPAL_NO_CACHE,//TODO 不起作用
        'status' => 1,
        'weight' => 0,
        'region' => 'Content',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => true,
    );
    $blocks['login']['properties']['administrative'] = TRUE;
}

/**
 * Implements hook_block_view().
 */
function login_block_view($delta = '')
{
    $module_path = drupal_get_path('module', 'login');
    if ($delta == 'login') {
        $block = array();
        $html = <<<EOS
        <main class="alignCenter">
		<section class="alignCenter marginBottom marginTop noFloat">
				<form>
					<table class="registration">
						<tr>
							<th colspan="2">
								<h1>登录</h1>
							</th>
							<tr>
								<td>
									<label class="alignLeft" for="email">用户名</label>
								</td>
								<td>
									<input class="alignRight" type="email" name="email">
								</td>
							</tr>
							<tr>
								<td>
									<label class="alignLeft" for="password">密码</label>
								</td>
								<td>
									<input class="alignRight" type="password" name="password">
								</td>
							</tr>
					</table>
					<div class="button">
						<a href="index.php">登录</a>
					</div>
					<p>
						<a href="register.php">注册？</a>
					</p>
				</form>
			</section>
	</main>
EOS;
        $block['content'] = $html;
        return $block;
    } 
}
